name: ds_client
description: An application to demo the distributed system
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  web_socket_channel: ^2.3.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: SFBold
      fonts:
        - asset: assets/sf-bold.otf
    - family: SFRegular
      fonts:
        - asset: assets/sf-regular.otf
